# === BEGIN DECLARING VARIABLES FOR USE IN MAKEFILE
# COMPILER
CC := gcc
CFLAGS := -Wall -Werror -c
DEBUG_FLAGS = -g

# DIRECTORIES
RELEASE_DIR := build/release
DEBUG_DIR := build/debug
OBJECTS_DIR := objects

RELEASE_OBJECTS_DIR := $(RELEASE_DIR)/$(OBJECTS_DIR)
DEBUG_OBJECTS_DIR := $(DEBUG_DIR)/$(OBJECTS_DIR)

SRC_DIR := src
INCLUDE_DIR := include

# SRC AND OBJ FILES
SRC_FILES := $(wildcard $(SRC_DIR)/*.c)

RELEASE_OBJ_FILES := $(patsubst $(SRC_DIR)/%.c,$(RELEASE_OBJECTS_DIR)/%.o,$(SRC_FILES))
DEBUG_OBJ_FILES := $(patsubst $(SRC_DIR)/%.c,$(DEBUG_OBJECTS_DIR)/%.o,$(SRC_FILES))

# ARCHIVING
ARCHIVER := ar
ARCHIVER_FLAGS := rc

INDEXER := ranlib

LIBRARY_NAME := liblina.a

RELEASE_LIBRARY := $(RELEASE_DIR)/$(LIBRARY_NAME)
DEBUG_LIBRARY := $(DEBUG_DIR)/$(LIBRARY_NAME)
# === END DECLARING VARIABLES FOR USE IN MAKEFILE

# === BEGIN PHONY TARGETS
.phony: release debug clean

release: $(RELEASE_LIBRARY)

debug: CFLAGS := $(CFLAGS) $(DEBUG_FLAGS)
debug: $(DEBUG_LIBRARY)

clean:
	@rm -rf build
# === END PHONY TARGETS

# === BEGIN LIBRARY TARGETS
$(RELEASE_LIBRARY): $(RELEASE_OBJ_FILES)
	$(ARCHIVER) $(ARCHIVER_FLAGS) $@ $?
	$(INDEXER) $@

$(DEBUG_LIBRARY): $(DEBUG_OBJ_FILES)
	$(ARCHIVER) $(ARCHIVER_FLAGS) $@ $?
	$(INDEXER) $@
# === END LIBRARY TARGETS

# === BEGIN OBJECT FILE TARGETS
$(RELEASE_OBJECTS_DIR)/%.o: $(SRC_DIR)/%.c $(INCLUDE_DIR)/*.h | $(RELEASE_OBJECTS_DIR)
	$(CC) $(CFLAGS) $< -o $@

$(DEBUG_OBJECTS_DIR)/%.o: $(SRC_DIR)/%.c $(INCLUDE_DIR)/*.h | $(DEBUG_OBJECTS_DIR)
	$(CC) $(CFLAGS) $< -o $@
# === END OBJECT FILE TARGETS

# === BEGIN DIRECTORY TARGETS
$(RELEASE_OBJECTS_DIR):
	@mkdir -p $(RELEASE_OBJECTS_DIR)

$(DEBUG_OBJECTS_DIR):
	@mkdir -p $(DEBUG_OBJECTS_DIR)
# === END DIRECTORY TARGETS



# ===
# NOTE: COMMENTED OUT LINES ARE FROM A FAILED IMPLEMENTATION AND ARE SAVED FOR
# 	A LATER REFACTOR
# ===

# BUILD_DIR = $(RELEASE_DIR)
#
# # === BEGIN DEFAULT BUILD
# all: $(LIBRARY_NAME)
# # === END DEFAULT BUILD
#
# # === BEGIN DEBUG TARGET
# debug: CFLAGS += -g
# debug: BUILD_DIR = $(DEBUG_DIR)
# debug: all
# # === END DEBUG TARGET
#
# # === BEGIN MAIN LIBRARY TARGET
# $(LIBRARY_NAME): $(OBJ_FILES)
# 	$(ARCHIVER) $(ARCHIVE_FLAGS) $(LIBRARY_NAME) $(OBJ_FILES)
# 	$(INDEXER) $(LIBRARY_NAME)
#
# $(OBJECTS_DIR)/%.o: src/%.c include/%.h | $(OBJECTS_DIR)
# 	$(CC) $(CFLAGS) $< -o $(OBJECTS_DIR)/$(@F)
#
# $(OBJECTS_DIR):
# 	@mkdir -p $(OBJECTS_DIR)
