# === BEGIN DECLARING VARIABLES FOR USE IN MAKEFILE
# COMPILER
CC := gcc
CFLAGS := -Wall -Werror -c
DEBUG_FLAGS = -g -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer

# DIRECTORIES
RELEASE_DIR := build/release
DEBUG_DIR := build/debug
OBJECTS_DIR := objects

RELEASE_OBJECTS_DIR := $(RELEASE_DIR)/$(OBJECTS_DIR)
DEBUG_OBJECTS_DIR := $(DEBUG_DIR)/$(OBJECTS_DIR)

SRC_DIR := src
INCLUDE_DIR := include

# SRC FILES, INCLUDE FILES, AND OBJ FILES
SRC_FILES := $(shell find $(SRC_DIR) -name "*.c")
INCLUDE_FILES := $(shell find $(INCLUDE_DIR) -name "*.h")

RELEASE_OBJ_FILES := $(patsubst $(SRC_DIR)/%.c,$(RELEASE_OBJECTS_DIR)/%.o,$(SRC_FILES))
DEBUG_OBJ_FILES := $(patsubst $(SRC_DIR)/%.c,$(DEBUG_OBJECTS_DIR)/%.o,$(SRC_FILES))

# ARCHIVING
ARCHIVER := ar
ARCHIVER_FLAGS := rc

INDEXER := ranlib

LIBRARY_BASE_NAME := lina
LIBRARY_NAME := lib$(LIBRARY_BASE_NAME).a

RELEASE_LIBRARY := $(RELEASE_DIR)/$(LIBRARY_NAME)
DEBUG_LIBRARY := $(DEBUG_DIR)/$(LIBRARY_NAME)
# === END DECLARING VARIABLES FOR USE IN MAKEFILE

# === BEGIN PHONY TARGETS
.phony: release debug clean

release: $(RELEASE_LIBRARY)

debug: CFLAGS := $(CFLAGS) $(DEBUG_FLAGS)
debug: $(DEBUG_LIBRARY)

clean:
	@rm -rf build
# === END PHONY TARGETS

# === BEGIN LIBRARY TARGETS
$(RELEASE_LIBRARY): $(RELEASE_OBJ_FILES) | $(RELEASE_DIR)
	$(ARCHIVER) $(ARCHIVER_FLAGS) $@ $?
	$(INDEXER) $@

$(DEBUG_LIBRARY): $(DEBUG_OBJ_FILES) | $(DEBUG_DIR)
	$(ARCHIVER) $(ARCHIVER_FLAGS) $@ $?
	$(INDEXER) $@
# === END LIBRARY TARGETS

# === BEGIN OBJECT FILE TARGETS
$(RELEASE_OBJECTS_DIR)/%.o: $(SRC_DIR)/%.c $(INCLUDE_FILES) 
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $< -o $@

$(DEBUG_OBJECTS_DIR)/%.o: $(SRC_DIR)/%.c $(INCLUDE_FILES) 
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $< -o $@
# === END OBJECT FILE TARGETS

